# Generated by Django 3.2.4 on 2021-06-22 12:29

from django.db import migrations, models
import tickets_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0003_alter_company_representative_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='people_limit',
            field=models.PositiveIntegerField(validators=[tickets_api.models.positive_decimal_validator]),
        ),
    ]
